version: '3.3'
services:
  front:
    image: ${PROJ_NAME}-front:latest
    container_name: ${PROJ_NAME}-front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/home/app
      - front-volume:/home/app/node_modules
    ports:
      - ${PROD_PORT_FRONT}:${PROD_PORT_FRONT}
      - ${DEV_PORT_FRONT}:${DEV_PORT_FRONT}
    tty: true
  back:
    image: ${PROJ_NAME}-back:latest
    container_name: ${PROJ_NAME}-back
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/app:/home/app
      - back-volume:/home/app/node_modules
    ports:
      - ${PROD_PORT_BACK}:${PROD_PORT_BACK}
      - ${DEV_PORT_BACK}:${DEV_PORT_BACK}
    depends_on:
      - postgre
    tty: true
  postgre:
    image: postgre-${PROJ_NAME}:latest
    container_name: postgre-${PROJ_NAME}
    build:
      context: ./postgre
      dockerfile: Dockerfile
    volumes:
      - ./postgre/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./postgre/db:/var/lib/postgresql/data
    ports:
      - ${PORT_POSTGRES}:${PORT_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  front-volume:
    name: ${PROJ_NAME}-front-volume
    driver: local
  back-volume:
    name: ${PROJ_NAME}-back-volume
    driver: local
